### ISSUE TITLE
One more `org.cqfn.diktat.ruleset.utils.KotlinParseException: Text is not valid`

### ISSUE THREAD

**Issue by petertrr** [analysis-dev/diktat#1141]
```
org.cqfn.diktat.ruleset.utils.KotlinParseException: Text is not valid: [""${window.location}/execution/$id" + if (status != null) "?status=$status" else """]
```
when trying to format
```kotlin
    private fun getHrefToExecution(id: Long, status: TestResultStatus?) =
        "${window.location}/execution/$id" + if (status != null) "?status=$status" else ""
```

Full stacktrace:
```
[ERROR] 2021-12-03 18:42:55 Internal error has occurred in rule [string-concatenation]. Please make an issue on this bug at https://github.com/cqfn/diKTat/. 
                       As a workaround you can disable these inspections in yml config: <[STRING_CONCATENATION]>.
                       Root cause of the problem is in [D:\projects\save-cloud\save-frontend\src\main\kotlin\org\cqfn\save\frontend\components\views\HistoryView.kt] file.
org.cqfn.diktat.ruleset.utils.KotlinParseException: Text is not valid: [""${window.location}/execution/$id" + if (status != null) "?status=$status" else """]
	at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode(KotlinParser.kt:75)
	at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode$default(KotlinParser.kt:75)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.fixBinaryExpressionWithConcatenation(StringConcatenationRule.kt:115)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.access$fixBinaryExpressionWithConcatenation(StringConcatenationRule.kt:31)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule$detectStringConcatenation$1.invoke(StringConcatenationRule.kt:65)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule$detectStringConcatenation$1.invoke(StringConcatenationRule.kt:61)
	at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix(Warnings.kt:260)
	at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix$default(Warnings.kt:202)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.detectStringConcatenation(StringConcatenationRule.kt:61)
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.logic(StringConcatenationRule.kt:44)
...
```

**Comment by akuleshov7** [comment]
@Cheshiriks should have fixed it in https://github.com/analysis-dev/diktat/pull/1183

**Comment by akuleshov7** [comment]
@Cheshiriks please check
