### ISSUE TITLE
KotlinParseException on string concatenation

### ISSUE THREAD

**Issue by Cheshiriks** [analysis-dev/diktat#1181]
Diktate falls in fix plugin on string concatenation: `"data:image/png;base64, " + state.image?.base64"`

```
[ERROR] 2022-01-21 17:53:17 Internal error has occurred in rule [string-concatenation]. Please make an issue on this bug at https://github.com/cqfn/diKTat/. 
                       As a workaround you can disable these inspections in yml config: <[STRING_CONCATENATION]>.
                       Root cause of the problem is in [C:\Users\vwx1020336\IdeaProjects\save-cloud-frontend\save-frontend\src\main\kotlin\org\cqfn\save\frontend\components\views\OwnerView.kt] file.
org.cqfn.diktat.ruleset.utils.KotlinParseException: Text is not valid: [""data:image/png;base64, " + state.image?.base64"]
	at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode(KotlinParser.kt:75) ~[diktat-rules-1.0.1.jar:?]
	at org.cqfn.diktat.ruleset.utils.KotlinParser.createNode$default(KotlinParser.kt:75) ~[diktat-rules-1.0.1.jar:?]
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.fixBinaryExpressionWithConcatenation(StringConcatenationRule.kt:115) ~[diktat-rules-1.0.1.jar:?]
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.access$fixBinaryExpressionWithConcatenation(StringConcatenationRule.kt:31) ~[diktat-rules-1.0.1.jar:?]
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule$detectStringConcatenation$1.invoke(StringConcatenationRule.kt:65) ~[diktat-rules-1.0.1.jar:?]
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule$detectStringConcatenation$1.invoke(StringConcatenationRule.kt:61) ~[diktat-rules-1.0.1.jar:?]
	at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix(Warnings.kt:261) ~[diktat-rules-1.0.1.jar:?]
	at org.cqfn.diktat.ruleset.constants.Warnings.warnAndFix$default(Warnings.kt:203) ~[diktat-rules-1.0.1.jar:?]
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.detectStringConcatenation(StringConcatenationRule.kt:61) ~[diktat-rules-1.0.1.jar:?]
	at org.cqfn.diktat.ruleset.rules.chapter3.StringConcatenationRule.logic(StringConcatenationRule.kt:44) ~[diktat-rules-1.0.1.jar:?]
	at org.cqfn.diktat.ruleset.rules.DiktatRule.visit(DiktatRule.kt:50) ~[diktat-rules-1.0.1.jar:?]
```

**Comment by akuleshov7** [comment]
Investigate and fix. We will take it into 1.0.3

**Comment by akuleshov7** [comment]
Issue happens on FIX only
