### ISSUE TITLE
Internal error has occurred in rule [lambda-length]

### ISSUE THREAD

**Issue by WebTiger89** [analysis-dev/diktat#1182]
My configuration without yml file:
`diktat {
    inputs {
        include("src/**/*.kts", "src/**/*.kts", "*.kts")
        exclude("build/**")
    }
    debug = true
}`

Kotlin version: 1.6.10
diktat version: 1.0.2

[ERROR] 2022-01-22 21:47:31 Internal error has occurred in rule [lambda-length]. Please make an issue on this bug at https://github.com/cqfn/diKTat/. 
                       As a workaround you can disable these inspections in yml config: <[TOO_MANY_LINES_IN_LAMBDA]>.
                       Root cause of the problem is in [...\configuration-plugin\build.gradle.kts] file.
java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.openapi.util.objectTree.ThrowableInterner
	at org.jetbrains.kotlin.com.intellij.util.exception.FrequentErrorLogger.report(FrequentErrorLogger.java:47) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.util.exception.FrequentErrorLogger.info(FrequentErrorLogger.java:43) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.handleUnspecifiedTrace(DebugUtil.java:628) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.currentInvalidationTrace(DebugUtil.java:620) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.calcInvalidationTrace(DebugUtil.java:614) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.onInvalidated(DebugUtil.java:585) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.TreeElement.onInvalidated(TreeElement.java:226) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.TreeElement.rawRemoveUpToWithoutNotifications(TreeElement.java:388) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.TreeElement.rawRemoveUpTo(TreeElement.java:342) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.CompositeElement.removeChildrenInner(CompositeElement.java:802) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.CompositeElement.removeChildInner(CompositeElement.java:790) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.CompositeElement.removeChild(CompositeElement.java:606) ~[kotlin-compiler-embeddable-1.6.10.jar:1.6.10-release-923(1.6.10)]
	at org.cqfn.diktat.ruleset.rules.chapter5.LambdaLengthRule.checkLambda(LambdaLengthRule.kt:39) ~[diktat-rules-1.0.2.jar:?]
	at org.cqfn.diktat.ruleset.rules.chapter5.LambdaLengthRule.logic(LambdaLengthRule.kt:29) ~[diktat-rules-1.0.2.jar:?]
	at org.cqfn.diktat.ruleset.rules.DiktatRule.visit(DiktatRule.kt:50) ~[diktat-rules-1.0.2.jar:?]
	at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:160) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:153) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:307) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:305) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:229) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:305) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:300) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:153) ~[ktlint-core-0.43.2.jar:?]
	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:172) ~[ktlint-0.43.2.jar:0.43.2]
	at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:395) ~[ktlint-0.43.2.jar:0.43.2]
	at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:89) ~[ktlint-0.43.2.jar:0.43.2]
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$3.invoke$lambda-0(Main.kt:289) ~[ktlint-0.43.2.jar:0.43.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.Error: Internal error in diktat application
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:576)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient java.lang.Object java.lang.Throwable.backtrace accessible: module java.base does not "opens java.lang" to unnamed module @24273305

	at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:548)
	at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:298)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:262)
	at com.pinterest.ktlint.Main.main(Main.kt:70)
Caused by: java.lang.Error: Internal error in diktat application
	at org.cqfn.diktat.ruleset.rules.DiktatRule.visit(DiktatRule.kt:61)
	at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:160)
	at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:153)
	at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:307)
	at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:305)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:229)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:230)
	at com.pinterest.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:305)
	at com.pinterest.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:300)
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:153)
	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:172)
	at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:395)
	at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:89)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$3.invoke$lambda-0(Main.kt:289)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.Error: Internal error in diktat application

**Comment by akuleshov7** [comment]
@WebTiger89 hello! Thank you for your report. We will investigate and return back to you. I suppose it will happen in several days. 😄

**Comment by petertrr** [comment]
@WebTiger89 could you please share the code, on which the error occurs? As is stated in the error message, the problem is in the file `configuration-plugin\build.gradle.kts`.

**Comment by akuleshov7** [comment]
@WebTiger89 just for the information, java.lang.NoClassDefFoundError is triggered in Kotlin with Java 17 on new M1 MAC. 
Is it that?

**Comment by WebTiger89** [comment]
Hi,
this is the content of my project-level build.gradle.kts:

`import io.gitlab.arturbosch.detekt.Detekt
import io.gitlab.arturbosch.detekt.DetektCreateBaselineTask

plugins {
    `kotlin-dsl` // Does use Kotlin v1.5.31 and is coupled to the Gradle version
    `maven-publish`
//    id("org.cqfn.diktat.diktat-gradle-plugin") version "1.0.2"
    id("com.github.ben-manes.versions") version "0.41.0"
    id("io.gitlab.arturbosch.detekt") version("1.19.0")
}

group = "de.mycompany.configuration"
version = "1.0"

// Bug, see: https://github.com/gradle/gradle/issues/18935
kotlinDslPluginOptions {
    jvmTarget.set("11")
}

//tasks.withType<KotlinCompile>().configureEach {
//    // Bug, see: https://github.com/gradle/gradle/issues/18935
//    kotlinOptions { jvmTarget = "1.8" }
//}

publishing {
    repositories {
        maven {
            url = uri("...")
            credentials(AwsCredentials::class) {
                accessKey = System.getenv("aws_access_key")
                secretKey = System.getenv("aws_secret_key")
            }
        }
    }
}

tasks.publish {
    dependsOn("check")
}

repositories {
    gradlePluginPortal()
    google()
    mavenCentral()
}

dependencies {
    implementation("com.android.tools.build:gradle:7.2.0-alpha07")
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10")
    implementation("com.github.ben-manes:gradle-versions-plugin:0.41.0")
    implementation("io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.19.0")
    detektPlugins("io.gitlab.arturbosch.detekt:detekt-formatting:1.19.0")
//    implementation("org.cqfn.diktat:diktat-gradle-plugin:1.0.2")
}

// Configure diktat
// see https://github.com/analysis-dev/diktat/issues/1182
//diktat {
//    inputs {
//        include("src/**/*.kt", "src/**/*.kts", "*.kts") // include src dir and project dir
//        exclude("build/**")
//    }
//    debug = true
//}

detekt {
    // Scan project dir for files
    source = files(projectDir)
    // Config file is built upon default
    buildUponDefaultConfig = true
    // Additional output on task execution
    debug = false
}

// Enable type resolution
tasks.withType<Detekt>().configureEach {
    this.jvmTarget = "1.8"
}
tasks.withType<DetektCreateBaselineTask>().configureEach {
    this.jvmTarget = "1.8"
}`

> IntelliJ IDEA 2021.3 (Ultimate Edition)
Build #IU-213.5744.223, built on November 27, 2021
Licensed to https://www.jiweichengzhu.com
You have a perpetual fallback license for this version.
Subscription is active until December 31, 2099.
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    detekt (1.19.0)
    org.jetbrains.kotlin (213-1.6.10-release-923-IJ5744.223)

Kotlin: 213-1.6.10-release-923-IJ5744.223

**Comment by akuleshov7** [comment]
@WebTiger89 is it MacOS? With M1?

Could you please share the small snippet of code where it can be reproduced?

**Comment by WebTiger89** [comment]
@akuleshov7 I'm not using any apple products. I'm on Windows 11.
[configuration-plugin.zip](https://github.com/analysis-dev/diktat/files/7924800/configuration-plugin.zip)

**Comment by petertrr** [comment]
@WebTiger89 could you please describe exact steps to reproduce the error? If I copy your `build.gradle.kts` and run either `diktatCheck` or `diktatFix`, build finishes successfully. Which task have you run, when you encountered the problem?

**Comment by WebTiger89** [comment]
@petertrr I have removed the .gradle and .idea folder, so only code remains. I start IntelliJ (OS and IDE informations at the top). I go to the Terminal section within IntelliJ and type _gradlew diktatCheck_ -> boom InternalError. I have removed every unnecessary line from my project-level build.gradle.kts -> no luck. Also tried to use embedded JDk instead of JDk 17 but still no luck.

What does the error message even state? I'm working in a vm but I doubt this information is relevant? Guest and Host OS is Windows 11.

![image](https://user-images.githubusercontent.com/26472588/150833650-6172b5bc-a35f-415f-8ad2-69c2ad16d5a2.png)

**Comment by WebTiger89** [comment]
When I remove the comment from
`
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    // Bug, see: https://github.com/gradle/gradle/issues/18935
    kotlinOptions { jvmTarget = "1.8" }
}
`
it works. Can you maybe explain that?
Off-topic questions:
1. Is it configurable to ignore failures?
2. Is it intended that diktatCheck task does not hook into check task?

**Comment by petertrr** [comment]
> What does the error message even state?

Something goes on incorrectly inside kotlin-compiler when we try to mutate the AST. It *might* be because gradle somehow overrides version and uses 1.6.10 instead of 1.5.31 (you can see it in stacktrace - `kotlin-compiler-embeddable-1.6.10.jar`).

> Only disabling it helps for now.

Yeah, that's because the error occurs during counting of lines.

> 1. Is it configurable to ignore failures?

You can suppress a lint error on a particular place using `@Suppress("TOO_MANY_LINES_IN_LAMBDA")`, for example. However, it won't help if there is an internal error.

> 2. Is it intended that diktatCheck task does not hook into check task?

Yes, we decided not to add this dependency to give users more freedom in how to configure their workflows. Personally, I prefer to run all checks separately in separate CI jobs, for example.

**Comment by WebTiger89** [comment]
@petertrr you can not reproduce it with my sample?

**Comment by petertrr** [comment]
Yep, I can reproduce the following error
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient java.lang.Object java.lang.Throwable.backtrace accessible: module java.base does not "opens java.lang" to unnamed module ...
```
on openjdk 16 and 17. Everything works fine on openjdk <15.
I also found the same issue tracked in ktlint: https://github.com/pinterest/ktlint/issues/1195.

As suggested there, the issue can be worked around by manually opening required JVM modules. With this fix in `build.gradle.kts`
```kotlin
tasks.withType<org.cqfn.diktat.plugin.gradle.DiktatJavaExecTaskBase> {
    jvmArgs("--add-opens", "java.base/java.lang=ALL-UNNAMED")
}
```
I was able to run you sample without this error.

**Comment by WebTiger89** [comment]
@petertrr cool, thanks for your time and investigation! I guess the ticket can be closed
